export const NAMES = {
  // Actions
  EDIT: 'edit',
  DELETE: 'delete',

  SEARCH: 'search',
  SEARCH_COMPANIES: 'search-companies',
  SEARCH_CONTACTS: 'search-contacts',
  SEARCH_EMAILS: 'search-emails',
  SEARCH_DRAFTS: 'search-drafts',
  SEARCH_SCHEDULED_EMAILS: 'search-scheduled-emails',
  SEARCH_SENDERS: 'search-senders',
  TEXT_COLOR: 'text-color',

  TITLE: 'title',
  DESCRIPTION: 'description',
  LOCATION: 'location',
  NAME: 'name',
  POSITION: 'position',
  EMAIL: 'email',
  PHONE: 'phone',
  LINKEDIN_URL: 'linkedInUrl',
  RECIPIENTS: 'recipients',
  SUBJECT: 'subject',
  IMAGE_UPLOAD: 'imageUpload',
  PROMPT: 'prompt',
  DISPLAY_NAME: 'displayName',
  ESP: 'esp',
  API_KEY: 'apiKey',
  PRIORITY: 'priority',
  TARGET: 'target',
}

export const LABELS = {
  // Actions
  EDIT: 'Edit',
  DELETE: 'Delete',
  ADD_NEW: '+ Add New',
  WRITE_NEW: '+ Write New',
  COMPOSE_NEW: '+ Compose New',
  COMPOSE: 'Compose',
  CANCEL: 'Cancel',
  SAVE: 'Save',
  SEND: 'Send',
  SEND_NOW: 'Send Now',
  GENERATE_EMAIL: 'Generate Email',

  COMPANIES: 'Companies',
  CONTACTS: 'Contacts',
  SENDERS: 'Senders',
  SENDER: 'Sender',
  EMAILS: 'Emails',
  SCHEDULED_EMAILS: 'Scheduled Emails',
  DRAFTS: 'Drafts',
  CREATED_AT: 'Created At',
  SENT_AT: 'Sent At',
  SAVE_DRAFT: 'Save Draft',
  SCHEDULE: 'Schedule',
  TO: 'To',
  SUBJECT: 'Subject',
  BODY: 'Body',
  PROMPT: 'Prompt',
  DISPLAY_NAME: 'Display Name',
  NAME: 'Name',
  API_KEY: 'API Key',
  PRIORITY: 'Priority',
  TARGET: 'Target',
  ESP: 'ESP',
  PROVIDER: 'Provider',

  ADD_NEW_COMPANY: 'Add New Company',
  ADD_NEW_CONTACT: 'Add New Contact',
  ADD_NEW_EMAIL: 'Add New Email',
  ADD_NEW_DRAFT: 'Add New Draft',
  ADD_NEW_SENDER: 'Add New Sender',

  ADD_COMPANY: 'Add Company',
  ADD_CONTACT: 'Add Contact',
  ADD_SENDER: 'Add Sender',
  ADD_DRAFT: 'Add Draft',

  EDIT_COMPANY: 'Edit Company',
  EDIT_CONTACT: 'Edit Contact',
  EDIT_EMAIL: 'Edit Email',
  EDIT_DRAFT: 'Edit Draft',
  EDIT_SENDER: 'Edit Sender',

  UPDATE_COMPANY: 'Update Company',
  UPDATE_CONTACT: 'Update Contact',
  UPDATE_DRAFT: 'Update Draft',
  UPDATE_SENDER: 'Update Sender',

  EDIT_TAG: 'Edit Tag',
  ADD_NEW_TAG: 'Add New Tag',

  COMPANY_NAME: 'Company Name',
  COMPANY_DESCRIPTION: 'Company Description',
  COMPANY_LOCATION: 'Company Location',

  TAGS: 'Tags',
  PROVIDERS: 'Providers',
  CONTACT_NAME: 'Contact Name',
  POSITION: 'Position',
  EMAIL: 'Email',
  PHONE: 'Phone',
  LINKEDIN_URL: 'LinkedIn URL',
  LOCATION: 'Location',
}

export const PLACEHOLDERS = {
  SEARCH: 'Search...',
  SEARCH_COMPANIES: 'Search Companies...',
  SEARCH_CONTACTS: 'Search Contacts...',
  SEARCH_EMAILS: 'Search Emails...',
  SEARCH_DRAFTS: 'Search Drafts...',
  SEARCH_SCHEDULED_EMAILS: 'Search Scheduled Emails...',
  SEARCH_SENDERS: 'Search Senders...',

  COMPANY_NAME: 'Enter company name',
  COMPANY_DESCRIPTION: 'Enter company description',
  COMPANY_LOCATION: 'Enter company location',

  TAGS: 'Select Tags',
  PROVIDERS: 'Select Providers',
  CONTACT_NAME: 'Enter Contact Name',
  POSITION: 'Enter Position',
  EMAIL: 'Enter Email',
  PHONE: 'Enter Phone',
  LINKEDIN_URL: 'Enter LinkedIn URL',
  LOCATION: 'Enter Location',
  EMAIL_SUBJECT: 'Enter Email Subject',
  EMAIL_BODY: 'Write Your Email Body Here!',
  RECIPIENTS: 'Enter Recipients',
  FONT_FAMILY: 'Font Family',
  ALIGNMENT: 'Align',
  CONTACTS: 'Select Contacts',
  SENDER: 'Select Sender',
  EMAIL_PROMPT: 'Enter Email Prompt',
  DISPLAY_NAME: 'Enter Display Name',
  NAME: 'Enter Name',
  API_KEY: 'Enter API Key',
  PRIORITY: 'Enter Priority',
  TARGET: 'Enter Target',
  ESP: 'Select ESP',
  PROVIDER: 'Select Provider',
}
