export const VALUES = {
  // Common
  COMMON_DATE_FORMAT: 'DD-MM-YYYY',
  SEARCH_QUERY_PARAM: 'q',
  PAGE_QUERY_PARAM: 'page',
  ESPS_QUERY_PARAM: 'providers',
  INITIAL_PAGE: 1,
  INITIAL_PAGE_PARAM: '1',
  INITIAL_ESPS_PARAM: '',
  INITIAL_SEARCH: '',
  INITIAL_SPINNER_SIZE: 24,

  // Layout
  HEADER_HEIGHT: 60,
  FOOTER_HEIGHT: 60,
  SIDEBAR_WIDTH: 240,

  // Pagination
  DEFAULT_PAGE_SIZE: 10,
  COMPANIES_PAGE_SIZE: 10,
  CONTACTS_PAGE_SIZE: 10,
  TAGS_PAGE_SIZE: 30,
  EMAILS_PAGE_SIZE: 10,
  DRAFTS_PAGE_SIZE: 10,
  SENDERS_PAGE_SIZE: 10,

  SEARCH_DEBOUNCE_DELAY: 500,
}
