export const VALUES = {
  // Common
  COMMON_DATE_FORMAT: 'DD-MM-YYYY',
  SEARCH_QUERY_PARAM: 'q',
  PAGE_QUERY_PARAM: 'page',
  ESPS_QUERY_PARAM: 'providers',
  EVENT_TYPES_QUERY_PARAM: 'events',
  INITIAL_PAGE: 1,
  INITIAL_PAGE_PARAM: '1',
  INITIAL_ESPS_PARAM: '',
  INITIAL_SEARCH: '',
  INITIAL_SPINNER_SIZE: 24,
  DEFAULT_PRIORITY: 1,
  DEFAULT_TARGET: 1000,

  // Layout
  HEADER_HEIGHT: 68,
  SIDEBAR_WIDTH: 240,
  SIDEBAR_ITEM_HEIGHT: 38,
  COLLAPSED_SIDEBAR_WIDTH: 70,
  HEADER_PADDING: 24,
  MAIN_CONTENT_PADDING: 24,
  SIDEBAR_TRANSITION_DURATION: '0.12s',
  SIDEBAR_LABEL_TRANSITION_DURATION: '0.08s',

  // Pagination
  DEFAULT_PAGE_SIZE: 10,
  COMPANIES_PAGE_SIZE: 10,
  CONTACTS_PAGE_SIZE: 10,
  TAGS_PAGE_SIZE: 30,
  EMAILS_PAGE_SIZE: 10,
  DRAFTS_PAGE_SIZE: 10,
  SENDERS_PAGE_SIZE: 10,

  SEARCH_DEBOUNCE_DELAY: 500,

  SUBJECT_IDENFIFIER: '---SUBJECT---',
  BODY_IDENFIFIER: '---BODY---',
}
