export const VALUES = {
  // Layout
  HEADER_HEIGHT: 60,
  FOOTER_HEIGHT: 60,
  SIDEBAR_WIDTH: 240,

  // Pagination
  DEFAULT_PAGE_SIZE: 10,
  COMPANIES_PAGE_SIZE: 10,
  CONTACTS_PAGE_SIZE: 10,
  EMAILS_PAGE_SIZE: 10,
  DRAFTS_PAGE_SIZE: 10,
  SENDERS_PAGE_SIZE: 10,
}
